function [ A_d,B_d ] = Linearized_Model(x,u,Ts)
%UNTITLED Summary of this function goes here
%   Detailed explanation goes here
    global m I_z l_f l_r C_f D_f D_r C_m1 C_m2 B_f B_r C_r C_d 
    % states X Y phi v_x v_y w
    %control delta d
    
    A_c =  ...
[ 0, 0, - x(5)*cos(x(3)) - x(4)*sin(x(3)),                                                                                                                                                                                                                                                                                                                                          cos(x(3)),                                                                                                                                                                                                                                                                                                        -sin(x(3)),                                                                                                                                                                                                                                                                                                                       0;
 0, 0,   x(4)*cos(x(3)) - x(5)*sin(x(3)),                                                                                                                                                                                                                                                                                                                                          sin(x(3)),                                                                                                                                                                                                                                                                                                         cos(x(3)),                                                                                                                                                                                                                                                                                                                       0;
 0, 0,                             0,                                                                                                                                                                                                                                                                                                                                                 0,                                                                                                                                                                                                                                                                                                                0,                                                                                                                                                                                                                                                                                                                       1;
 0, 0,                             0,                                                                                                                                                             -(C_m2*u(1) + 2*C_d*x(4) + (B_r*C_r*D_r*cos(C_r*atan(B_r*atan((x(5) - l_r*x(6))/x(4))))*sin(u(1))*(x(5) - l_r*x(6)))/(x(4)^2*((x(5) - l_r*x(6))^2/x(4)^2 + 1)*(B_r^2*atan((x(5) - l_r*x(6))/x(4))^2 + 1)))/m,                                                                                                                                                            (m*x(6) + (B_r*C_r*D_r*cos(C_r*atan(B_r*atan((x(5) - l_r*x(6))/x(4))))*sin(u(1)))/(x(4)*((x(5) - l_r*x(6))^2/x(4)^2 + 1)*(B_r^2*atan((x(5) - l_r*x(6))/x(4))^2 + 1)))/m,                                                                                                                                                             (m*x(5) - (B_r*C_r*D_r*l_r*cos(C_r*atan(B_r*atan((x(5) - l_r*x(6))/x(4))))*sin(u(1)))/(x(4)*((x(5) - l_r*x(6))^2/x(4)^2 + 1)*(B_r^2*atan((x(5) - l_r*x(6))/x(4))^2 + 1)))/m;
 0, 0,                             0,      ((B_r*C_r*D_r*cos(C_r*atan(B_r*atan((x(5) - l_r*x(6))/x(4))))*(x(5) - l_r*x(6)))/(x(4)^2*((x(5) - l_r*x(6))^2/x(4)^2 + 1)*(B_r^2*atan((x(5) - l_r*x(6))/x(4))^2 + 1)) - m*x(6) + (B_f*C_f*D_f*cos(u(1))*cos(C_f*atan(B_f*(u(1) - atan((x(5) + l_f*x(6))/x(4)))))*(x(5) + l_f*x(6)))/(x(4)^2*((x(5) + l_f*x(6))^2/x(4)^2 + 1)*(B_f^2*(u(1) - atan((x(5) + l_f*x(6))/x(4)))^2 + 1)))/m,          -((B_r*C_r*D_r*cos(C_r*atan(B_r*atan((x(5) - l_r*x(6))/x(4)))))/(x(4)*((x(5) - l_r*x(6))^2/x(4)^2 + 1)*(B_r^2*atan((x(5) - l_r*x(6))/x(4))^2 + 1)) + (B_f*C_f*D_f*cos(u(1))*cos(C_f*atan(B_f*(u(1) - atan((x(5) + l_f*x(6))/x(4))))))/(x(4)*((x(5) + l_f*x(6))^2/x(4)^2 + 1)*(B_f^2*(u(1) - atan((x(5) + l_f*x(6))/x(4)))^2 + 1)))/m, -(m*x(4) - (B_r*C_r*D_r*l_r*cos(C_r*atan(B_r*atan((x(5) - l_r*x(6))/x(4)))))/(x(4)*((x(5) - l_r*x(6))^2/x(4)^2 + 1)*(B_r^2*atan((x(5) - l_r*x(6))/x(4))^2 + 1)) + (B_f*C_f*D_f*l_f*cos(u(1))*cos(C_f*atan(B_f*(u(1) - atan((x(5) + l_f*x(6))/x(4))))))/(x(4)*((x(5) + l_f*x(6))^2/x(4)^2 + 1)*(B_f^2*(u(1) - atan((x(5) + l_f*x(6))/x(4)))^2 + 1)))/m;
 0, 0,                             0, -((B_r*C_r*D_r*l_r*cos(C_r*atan(B_r*atan((x(5) - l_r*x(6))/x(4))))*(x(5) - l_r*x(6)))/(x(4)^2*((x(5) - l_r*x(6))^2/x(4)^2 + 1)*(B_r^2*atan((x(5) - l_r*x(6))/x(4))^2 + 1)) - (B_f*C_f*D_f*l_f*cos(u(1))*cos(C_f*atan(B_f*(u(1) - atan((x(5) + l_f*x(6))/x(4)))))*(x(5) + l_f*x(6)))/(x(4)^2*((x(5) + l_f*x(6))^2/x(4)^2 + 1)*(B_f^2*(u(1) - atan((x(5) + l_f*x(6))/x(4)))^2 + 1)))/I_z, ((B_r*C_r*D_r*l_r*cos(C_r*atan(B_r*atan((x(5) - l_r*x(6))/x(4)))))/(x(4)*((x(5) - l_r*x(6))^2/x(4)^2 + 1)*(B_r^2*atan((x(5) - l_r*x(6))/x(4))^2 + 1)) - (B_f*C_f*D_f*l_f*cos(u(1))*cos(C_f*atan(B_f*(u(1) - atan((x(5) + l_f*x(6))/x(4))))))/(x(4)*((x(5) + l_f*x(6))^2/x(4)^2 + 1)*(B_f^2*(u(1) - atan((x(5) + l_f*x(6))/x(4)))^2 + 1)))/I_z,   -((B_r*C_r*D_r*l_r^2*cos(C_r*atan(B_r*atan((x(5) - l_r*x(6))/x(4)))))/(x(4)*((x(5) - l_r*x(6))^2/x(4)^2 + 1)*(B_r^2*atan((x(5) - l_r*x(6))/x(4))^2 + 1)) + (B_f*C_f*D_f*l_f^2*cos(u(1))*cos(C_f*atan(B_f*(u(1) - atan((x(5) + l_f*x(6))/x(4))))))/(x(4)*((x(5) + l_f*x(6))^2/x(4)^2 + 1)*(B_f^2*(u(1) - atan((x(5) + l_f*x(6))/x(4)))^2 + 1)))/I_z];
 
 
B_c = ...
[                                                                                                                                                                                                                  0,                   0;
                                                                                                                                                                                                                  0,                   0;
                                                                                                                                                                                                                  0,                   0;
                                                                                                                                                      (D_r*cos(u(1))*sin(C_r*atan(B_r*atan((x(5) - l_r*x(6))/x(4)))))/m, (C_m1 - C_m2*x(4))/m;
           -(D_f*sin(u(1))*sin(C_f*atan(B_f*(u(1) - atan((x(5) + l_f*x(6))/x(4))))) - (B_f*C_f*D_f*cos(u(1))*cos(C_f*atan(B_f*(u(1) - atan((x(5) + l_f*x(6))/x(4))))))/(B_f^2*(u(1) - atan((x(5) + l_f*x(6))/x(4)))^2 + 1))/m,                   0;
 -(D_f*l_f*sin(u(1))*sin(C_f*atan(B_f*(u(1) - atan((x(5) + l_f*x(6))/x(4))))) - (B_f*C_f*D_f*l_f*cos(u(1))*cos(C_f*atan(B_f*(u(1) - atan((x(5) + l_f*x(6))/x(4))))))/(B_f^2*(u(1) - atan((x(5) + l_f*x(6))/x(4)))^2 + 1))/I_z,                   0];
                                                                                               
C_c = eye(6);
D_c = zeros(6,2);

sys_c = ss(A_c,B_c,C_c,D_c);
sys_d = c2d(sys_c,Ts);
A_d = sys_d.A;
B_d = sys_d.B;
                                                                                           
 
 

end

